name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sympy
    - name: Checkout code
      uses: actions/checkout@v4
    - name: ".tests /import_test.py"
      id: tests-import_test-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: ''
    - name: ".tests /balance_test.py"
      id: tests-balance_test-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-IMPORT_TEST-PY_RESULTS: "${{steps.tests-import_test-py.outputs.result}}"
        TESTS-BALANCE_TEST-PY_RESULTS: "${{steps.tests-balance_test-py.outputs.result}}"
      with:
        runners: tests-import_test-py,tests-balance_test-py
